### ISSUE TITLE
views.py invokes a string method on an int

### ISSUE THREAD

**Issue by wlscanada** [nutechsoftware/alarmdecoder-webapp#43]
Traceback:

File "/opt/alarmdecoder-webapp/ad2web/settings/views.py", line 717, in system_diagnostics
device_settings['serial'] = current_app.decoder.device.serial_number.upper()

However, in alarmdecoder's decoder.py, serial_number is defined as an int.

**Comment by f34rdotcom** [comment]
I am guessing this is the error? 
   AttributeError: 'int' object has no attribute 'upper'

I see the value is initialized in decoder.py as 0xffffffff an int value. Yet later on it is replaced with the AD2* serial number info from a 'V' version command. This field is alpha numeric. I see the issue as the constructor needs to be changed to 'Unknown'. I also think this upper() needs to be removed and just presented as is to the webapp settings database.

Fixed in dev.

**Comment by wlscanada** [comment]
That is indeed the error.  I just did a clone --branch dev however and the problem is still there?

**Comment by f34rdotcom** [comment]
Hmm maybe the code is some place else on the system and not running from your local git repo. This may have happend if it were "installed" onto the system by running "python setup.py" I have net to confirm this but I believe I have seen this issue on some older versions or systems where again the operator had installed it at some point and it is not just running from the git folder as being in the python path. If the error and line number in the event are the same and do not match the line in the "dev" branch then this would be likely the issue.

**Comment by wlscanada** [comment]
Ah, I cloned dev of alarmdecoder-webapp rather than alarmdecoder.  That being said, I am still seeing this error... how should I install if not (alternative to) using python setup.py?

**Comment by f34rdotcom** [comment]
Excellent! thanks for the help in testing.
